{% set name = "decorrelation" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decorrelation-{{ version }}.tar.gz
  sha256: bdc067aacc3088a542a5a177291d4a537391fcd0d94c6cbf80b6e297ee563068

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base
    - dask
    - colorcet
    - zarr

test:
  imports:
    - decorrelation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/decorrelation
  summary: An InSAR postprocessing tool
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
