{% set name = "decorrelation" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decorrelation-{{ version }}.tar.gz
  sha256: 0a52f65e908f2f6f2ce9d1edf2bc0abaccaef4c54d6d2c3c0acd541494435dcd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base
    - dask
    - colorcet
    - zarr
    - fastcore
    - pandas
    - toml

test:
  imports:
    - decorrelation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/decorrelation
  summary: An InSAR postprocessing tool
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
