{% set name = "decorrelation" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decorrelation-{{ version }}.tar.gz
  sha256: e71598b04516374730f026d02cca28c73dfe32285ebb2fbd8af0697bd2bd9614

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib
    - numba
    - datashader
    - holoviews
    - numexpr
    - pyproj >=3.0
    - dask
    - colorcet
    - zarr
    - fastcore
    - pandas
    - toml

test:
  imports:
    - decorrelation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/decorrelation
  summary: An InSAR postprocessing tool
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
